apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: orchestrator-backstage
  title: Orchestartor backstage deployed by argocd
  description: |
    Orchestartor backstage deployed by argocd
  annotations:
    backstage.io/kubernetes-id: 'orchestrator-backstage'
    backstage.io/kubernetes-namespace: 'default'
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=backstage'
    argocd/app-selector: 'app=orchestrator'
spec:
  type: service
  system: orchestrator-backend
  owner: orchestrator-team
  lifecycle: production
